parameters:
- name: poolname
  displayName: Select Pool Name
  type: string
  default: Azure Pipelines
  values:
  - Default
  - Azure Pipelines
- name: agent
  displayName: Select Agent 
  type: string
  default: Hosted Agent
  values:
  - private-agent
  - Hosted Agent
  - demo-linux-pr-agent
# - name: rgname
#   displayName: Provide resource group name 
#   type: string
# - name: location
#   displayName: Provide resource group location
#   type: string

trigger: none


stages:
- stage: Infradeployment
  jobs:
  - job: ci
    displayName: infra-creation
    pool: 
      name: ${{ parameters.poolname }}
      demands:
      - agent.name -equals ${{ parameters.agent }}
    steps:
    - task: AzureCLI@2
      displayName: 'Run Az command'
      inputs:
        azureSubscription:
        scriptType: 'batch'
        scriptLocation: 'inlineScript'
        inlineScript: |
            echo "Deattaching data disk"
            az vm disk detach -g terraform-demo-rg --vm-name demo-tf-auto-vm --name DemoDisk2
            echo "Deleting data disk"
            az disk delete -g azurerm_resource_group -n DemoDisk2 --size-gb 10 --location eastus --sku Standard_LRS
            