parameters:
- name: poolname
  displayName: Select Pool Name
  type: string
  default: Azure Pipelines
  values:
  - private-agent
  - Default
  - Azure Pipelines
  - Demo-pvt-agent
# - name: env
#   displayName: Select your Environment
#   type: string
#   default: dev
#   values:
#   - dev
#   - test
#   #- preprod
#   - prod
- name: agent
  displayName: Select Agent 
  type: string
  default: Hosted Agent
  values:
  - private-agent
  - Hosted Agent
  - demo-linux-pr-agent
  - ajay-vm-1
  - demoagentbatch2
- name: rgname
  displayName: Provide resource group name 
  type: string
- name: location
  displayName: Provide resource group location
  type: string

trigger: none

# variables:
# - group: Dev-env-details


stages:
- stage: InfraCI
  jobs:
  - job: ci
    displayName: build
    pool: 
      name: ${{ parameters.poolname }}
      demands:
      - agent.name -equals ${{ parameters.agent }}


    steps:
    - task: CopyFiles@2
      displayName: 'Checkout infra code'
      inputs:
        SourceFolder: $(source_path)
        #SourceFolder: infra
        Contents: '**/**'
        TargetFolder: '$(build.artifactstagingdirectory)'