parameters:
- name: poolname
  displayName: Select Pool Name
  type: string
  default: Azure Pipelines
  values:
  - Default
  - Azure Pipelines
- name: agent
  displayName: Select Agent 
  type: string
  default: Hosted Agent
  values:
  - private-agent
  - Hosted Agent
  - demo-linux-pr-agent
- name: images
  displayName: image
  type: string
  default: ubuntu-latest
  values:
  - windows-latest
  - vs2017-win2016
  - ubuntu-latest

trigger: none


stages:
- stage: Infradeployment
  jobs:
  - job: ci
    displayName: infra-creation
    pool: 
      vmImage: ${{ parameters.images }}
      name: ${{ parameters.poolname }}

    steps:
    - task: AzureCLI@2
      displayName: 'Run Az command'
      inputs:
        azureSubscription:
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          echo "Deattaching data disk"
          az vm disk detach -g terraform-demo-rg --vm-name demo-tf-auto-vm --name DemoDisk2
          echo "Deleting data disk"
          az disk delete -g azurerm_resource_group -n DemoDisk2 --size-gb 10 --location eastus --sku Standard_LRS
            